using System;

namespace ZeroData.Sql.Mapping
{
    /// <summary>
    /// Specifies the synchronization behavior for auto-generated columns.
    /// Compatible with System.Data.Linq.Mapping.AutoSync.
    /// </summary>
    public enum AutoSync
    {
        Default = 0,
        Always = 1,
        Never = 2,
        OnInsert = 3,
        OnUpdate = 4
    }

    /// <summary>
    /// Maps a property to a database column.
    /// Compatible with System.Data.Linq.Mapping.ColumnAttribute.
    /// </summary>
    [AttributeUsage(AttributeTargets.Property | AttributeTargets.Field, AllowMultiple = false)]
    public sealed class ColumnAttribute : Attribute
    {
        /// <summary>
        /// Gets or sets the name of the column in the database.
        /// If not specified, the property name is used.
        /// </summary>
        public string Name { get; set; }

        /// <summary>
        /// Gets or sets the type of the database column.
        /// </summary>
        public string DbType { get; set; }

        /// <summary>
        /// Gets or sets whether this column is the primary key.
        /// </summary>
        public bool IsPrimaryKey { get; set; }

        /// <summary>
        /// Gets or sets whether this column value is auto-generated by the database
        /// (e.g., IDENTITY or computed columns).
        /// </summary>
        public bool IsDbGenerated { get; set; }

        /// <summary>
        /// Gets or sets whether this column can contain null values.
        /// </summary>
        public bool CanBeNull { get; set; } = true;

        /// <summary>
        /// Gets or sets a value that specifies how the column is synchronized
        /// after an insert or update operation.
        /// </summary>
        public AutoSync AutoSync { get; set; } = AutoSync.Default;

        /// <summary>
        /// Gets or sets the storage field name for the property value.
        /// Compatible with L2S designer-generated code.
        /// </summary>
        public string Storage { get; set; }

        /// <summary>
        /// Gets or sets whether this column participates in optimistic concurrency checks.
        /// </summary>
        public UpdateCheck UpdateCheck { get; set; } = UpdateCheck.Always;

        /// <summary>
        /// Gets or sets whether this column holds a discriminator value for inheritance.
        /// </summary>
        public bool IsDiscriminator { get; set; }

        /// <summary>
        /// Gets or sets the member access expression for computed or derived values.
        /// </summary>
        public string Expression { get; set; }

        /// <summary>
        /// Gets or sets whether this column is a version/timestamp column.
        /// </summary>
        public bool IsVersion { get; set; }
    }

    /// <summary>
    /// Specifies when to check for optimistic concurrency conflicts.
    /// Compatible with System.Data.Linq.Mapping.UpdateCheck.
    /// </summary>
    public enum UpdateCheck
    {
        Always = 0,
        Never = 1,
        WhenChanged = 2
    }
}
