// <auto-generated />
// Generated by LiteSql - Query Extensions
// Date: 2026-04-02 14:30:46
// Inspired by SqlSugar and FreeSql patterns

using System;
using System.Linq.Expressions;

namespace ZeroData.Sql
{
    /// <summary>
    /// Extension methods for conditional query building.
    /// Inspired by SqlSugar's WhereIF and FreeSql's WhereIf patterns.
    /// </summary>
    public static class QueryExtensions
    {
        /// <summary>
        /// Conditionally applies a WHERE clause based on a boolean condition.
        /// If condition is false, returns the table unchanged.
        /// </summary>
        /// <example>
        /// var query = db.Orders
        ///     .WhereIf(!string.IsNullOrEmpty(status), o => o.Status == status)
        ///     .WhereIf(minAmount.HasValue, o => o.Amount >= minAmount.Value);
        /// </example>
        public static Table<T> WhereIf<T>(
            this Table<T> table,
            bool condition,
            Expression<Func<T, bool>> predicate) where T : class
        {
            if (condition)
            {
                table.AddPendingPredicate(predicate);
            }
            return table;
        }

        /// <summary>
        /// Conditionally applies a HAVING clause to a GroupBy query based on a boolean condition.
        /// If condition is false, returns the query unchanged.
        /// </summary>
        public static GroupByQuery<T, TKey> WhereIf<T, TKey>(
            this GroupByQuery<T, TKey> query,
            bool condition,
            Expression<Func<System.Linq.IGrouping<TKey, T>, bool>> predicate) where T : class
        {
            return condition ? query.Where(predicate) : query;
        }
    }
}
